.TH "XD\-DEPLOY" "1" "January 2020" "" ""
.SH "NAME"
\fBxd-deploy\fR \- A network plugin manager for Adobe XD
.SH SYNOPSIS
.P
\fBxd\-deploy\fP <command> [options\.\.\.]
.SH DESCRIPTION
.P
\fBxd\-deploy\fP is a Node\-Based network plugin manager for Adobe XD CC\.
.P
It allows to install plugins on multiple machines running Adobe XD simaltaniously during development\.
.SH INSTALL
.P
The CLI can get installed with \fBnpm\fP:
.P
.RS 2
.nf
npm install \-g @pklaschka/xd\-deploy
.fi
.RE
.SH ARCHITECTURE
.P
\fBxd\-deploy\fP consists of at least three systems:
.RS 0
.IP \(bu 2
\fBserver\fR: running in a network accessible for both \fIclient\fR and \fIdev client\fR\|\. Responsible for distributing plugins to \fIclients\fR
.IP \(bu 2
\fBclient\fR: running on a machine with Adobe XD\. Installs plugins from \fBserver\fR in Adobe XD's develop folder
.IP \(bu 2
\fBdev client\fR: running on the development machine, this sends the plugin to the \fIserver\fR for distribution

.RE
.SH COMMANDS
.P
<command> is one of the three commands \fBserver\fP, \fBclient\fP or \fBdev\fP 
which lets you start the corresponding service:
.SS \fBserver\fP
.P
\fBxd\-deploy\fP \fBserver\fP [args\.\.\.]
.P
Start the \fBserver\fR\|\.
.P
Arguments:
.RS 0
.IP \(bu 2
\fB\-p\fP=<port>, \fB\-\-port\fP=<port>:
Use the specified <port>, or, if none is specified, 8080\.

.RE
.SS \fBclient\fP
.P
\fBxd\-deploy\fP \fBclient\fP <serverLocation>
.P
Start the client\. Installs plugins form \fBserver\fR at <serverLocation> (full url)\.
.SS \fBdev\fP (alias: \fBdevelop\fP)
.P
\fBxd\-deploy\fP \fBdev\fP <mode> <serverLocation> [pluginFolder]
.P
Start the developer server for the plugin in [pluginFolder] (the CWD, if none is specified)\.
.P
Mode can be \fBinstall\fP (resulting in the plugin getting installed once) or \fBwatch\fP, meaning the plugin folder will get watched for changes after the initial install and the plugin gets reinstalled on change\.
.SH EXAMPLES
.RS 0
.IP \(bu 2
\fBxd\-deploy\fP \fBserver\fP \fB\-\-port\fP \fB3000\fP:
Start the \fBserver\fR on port 3000
.IP \(bu 2
\fBxd\-deploy\fP \fBclient\fP \fBhttp://localhost:3000\fP:
Start the \fBclient\fR and connect to the server on http://localhost:3000
.IP \(bu 2
\fBxd\-deploy\fP \fBdev\fP \fBinstall\fP \fBhttp://localhost:3000\fP \fB\|\./plugin\fP:
Install (once) the plugin in \./plugin on the server running on http://localhost:3000
.IP \(bu 2
\fBxd\-deploy\fP \fBdev\fP \fBwatch\fP \fBhttp://localhost:3000\fP \fB\|\./plugin\fP:
Install the plugin in \./plugin on the server running on http://localhost:3000\. Watch for changes and reinstall on change\.

.RE
.SH AUTHOR
.P
Pablo Klaschka xdplugins@pabloklashcka\.de

